# kube service 4 hybris56
apiVersion: v1
kind: Service
metadata:
  name: hybris56-service
  labels:
    app: hybris56-service
spec:
  ports:
  - name: http
    port: 9001
    targetPort: 9001
  - name: https
    port: 9002
    targetPort: 9002
  - name: debug
    port: 8000
    targetPort: 8000
  selector:
    app: hybris56
