apiVersion: v1
kind: ReplicationController
namespace: default
metadata:
  name: zk-controller
spec:
  replicas: 1
  selector:
    app: zookeeper
  template:
    metadata:
      labels:
        app: zookeeper
    spec:
      containers:
      - name: zookeeper
        image: apache/zookeeper
        ports:
        - containerPort: 2181
        - containerPort: 2888
        - containerPort: 3888
        volumeMounts:
        - name: zk-data
          mountPath: /var/run/zookeeper/data
      volumes:
      - name: zk-data
        emptyDir: {}
